# Use an official Python 3.10 base image
FROM python:3.10-slim

# Set environment variables to reduce output and enable UTF-8
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV LANG=C.UTF-8

# Install system dependencies
RUN apt-get update && apt-get install -y \
    openjdk-17-jre-headless \ 
    openfortivpn \ 
    unixodbc \
    unixodbc-dev \
    iproute2 \
    curl \
    build-essential && \
    apt-get purge -y build-essential && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/*

# Install Microsoft ODBC Driver 17 for SQL Server (for pyodbc)
RUN apt-get update && \
    apt-get install -y curl gnupg2 apt-transport-https && \
    mkdir -p /etc/apt/sources.list.d && \
    curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg && \
    install -o root -g root -m 644 microsoft.gpg /etc/apt/trusted.gpg.d/ && \
    curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list -o /etc/apt/sources.list.d/mssql-release.list && \
    rm microsoft.gpg && \
    apt-get update && \
    ACCEPT_EULA=Y apt-get install -y msodbcsql17 unixodbc unixodbc-dev && \
    apt-get clean


# Set JAVA_HOME for Tika
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH="$JAVA_HOME/bin:$PATH"

# Create app directory
WORKDIR /app

# VPN config
COPY config /etc/openfortivpn/config
RUN chmod 600 /etc/openfortivpn/config

# Copy requirements into image
COPY requirements.txt .

# Install Python dependencies
RUN pip install --upgrade pip \
 && pip install --no-cache-dir torch==2.2.2+cpu torchvision==0.17.2+cpu torchaudio==2.2.2+cpu \
      -f https://download.pytorch.org/whl/cpu/torch_stable.html \
 && pip install --no-cache-dir -r requirements.txt \
 && python -m pip uninstall -y pip


# Copy project files
COPY ./src/. .

# Copy entry point
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 8000

CMD ["/entrypoint.sh"]